### ISSUE TITLE
Analog video sync is out of range

### ISSUE THREAD

**Issue by Gillaxian** [va7deo/PrehistoricIsle#1]
For analog video, the horizontal and vertical sync (positioning) settings are a bit out of range to get centered on screen.  At default the sync is far to the right and down. Even setting it at the furthest left and up position still doesn't get the image centered on screen.

**Comment by atrac17** [comment]
Fixed in [6c0b243](https://github.com/va7deo/PrehistoricIsle/commit/6c0b24379365921be7b9437fd690158de589ea27). You can further position with H-Sync / V-Sync Width adjustments and screen centering should be better. This game has a bizarre refresh and may require vertical adjustments on pots for your cabs.
